// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: testhello.proto

package test

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NewGreeterClient is the client API for NewGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewGreeterClient interface {
	SayHello(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error)
}

type newGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewNewGreeterClient(cc grpc.ClientConnInterface) NewGreeterClient {
	return &newGreeterClient{cc}
}

func (c *newGreeterClient) SayHello(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error) {
	out := new(TestReply)
	err := c.cc.Invoke(ctx, "/proto.NewGreeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewGreeterServer is the server API for NewGreeter service.
// All implementations must embed UnimplementedNewGreeterServer
// for forward compatibility
type NewGreeterServer interface {
	SayHello(context.Context, *TestRequest) (*TestReply, error)
	mustEmbedUnimplementedNewGreeterServer()
}

// UnimplementedNewGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedNewGreeterServer struct {
}

func (UnimplementedNewGreeterServer) SayHello(context.Context, *TestRequest) (*TestReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedNewGreeterServer) mustEmbedUnimplementedNewGreeterServer() {}

// UnsafeNewGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewGreeterServer will
// result in compilation errors.
type UnsafeNewGreeterServer interface {
	mustEmbedUnimplementedNewGreeterServer()
}

func RegisterNewGreeterServer(s grpc.ServiceRegistrar, srv NewGreeterServer) {
	s.RegisterService(&NewGreeter_ServiceDesc, srv)
}

func _NewGreeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewGreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NewGreeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewGreeterServer).SayHello(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NewGreeter_ServiceDesc is the grpc.ServiceDesc for NewGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NewGreeter",
	HandlerType: (*NewGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _NewGreeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testhello.proto",
}
